---
language: ruby
rvm:
- 1.9.3
gemfile:
- spec/support/Gemfile
script:
- bundle exec rake spec
- bundle exec rake foodcritic
notifications:
  email:
    recipients:
    - github+modcloth-nad-cookbook@modcloth.com
